global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alexmrasir@gmail.com'
  smtp_auth_username: 'alexmrasir@gmail.com'
  smtp_auth_password: 'qqwf btti ekmm iubx'

route:
  receiver: 'correo-gmail'
  group_by: ['alertmanager']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m

receivers:
  - name: 'correo-gmail'
    email_configs:
      - to: 'alexmrasir@gmail.com'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
